- name: "Remove unneded config dirs"
  file:
    status: absent
  loop:
    - "/etc/nginx/sites-enabled"
    - "/etc/nginx/sites-available"
  ignore_errors: true

- name: "Install nginx main config"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: "Reload nginx"

- name: "Install upstream configs"
  template:
    src: "upstream.conf.j2"
    dest: "/etc/nginx/conf.d/upstream_{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ nginx_upstreams }}"
  notify: "Reload nginx"

- name: "Install vhost configs"
  template:
    src: "upstream.conf.j2"
    dest: "/etc/nginx/conf.d/vhost_{{ item.server_name[0] }}.conf"
    owner: root
    group: root
    mode: 0644
  loop: "{{ nginx_vhosts }}"
  notify: "Reload nginx"

- name: "Install nginx ssl config"
  template: 
    src: "ssl.conf.j2"
    dest: "{{ nginx_ssl_config_snippet_path }}"
    owner: root
    group: root
    mode: 0644
  when: nginx_bind_https
  notify: "Reload nginx"

- name: "Remove unneded ssl config"
  file: 
    path: "{{ nginx_ssl_config_snippet_path }}"
    state: absent
  when: not nginx_bind_https
