- name: "Check configuration"
  assert:
    that:
      - ipam.keys()|length > 0
      - ipam_networks.keys()|length > 0

- name: "Install nginx"
  apt:
    name: nginx
    state: present
    update_cache: true

- name: "Setup configs"
  import_tasks: config.yaml

- name: "Setup static host dirs"
  import_tasks: static.yaml
  when: nginx_manage_static_root_dirs

- name: "Setup unified cert integration"
  import_tasks: unified_cert_integration.yaml
  when: nginx_integrate_unified_cert

# This should be added to the end of every role, since ansible can't scope handlers for a role
- name: "Flush handlers at the end of the role"
  meta: flush_handlers
