- name: "Make sure Marcsello Corp.(r) unified certificate folder(s) exists"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "/etc/certs"
    - "/etc/certs/hooks"

- name: "Install Marcsello Corp.(r) unified certificate integration"
  copy:
    src: "99-reload-nginx"
    dest: "/etc/certs/hooks/99-reload-nginx"
    mode: 0755
    owner: root
    group: root
