- name: "Install haproxy"
  apt:
    name: haproxy
    state: present
    update_cache: true

- name: "Install config"
  template:
    src: "haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: 0644
  notify: "Reload haproxy"

# This should be added to the end of every role, since ansible can't scope handlers for a role
- name: "Flush handlers at the end of the role"
  meta: flush_handlers
