haproxy_frontends: 
  - name: "service_https"
    config: | 
      bind :::443 v4v6
      mode tcp
      default_backend nginx

  - name: "service_http"
    config: |
      bind :::80 v4v6
      mode http
      http-request redirect scheme https unless { path -i -m beg /.well-known/acme-challenge }
      default_backend acme


haproxy_backends: 
 - name: "nginx"
   config: |
    mode tcp
    option tcp-check
    server local 127.0.0.1:8443 check
    server other {{ ipam[haproxy_custom_pair]['service_addr']['ip'] }}:8443 check

 - name: "acme"
   config: |
    mode http
    server acme {{ ipam.maud.service_addr.ip }}:80 check
