nginx_manage_static_root_dirs: false
nginx_https_proxy_protocol: true
nginx_integrate_unified_cert: true

stevenmagnet_full_domain: "stevenmagnet{{ ipam_networks[ipam.stevenmagnet.network]['domain'] }}"
violet_full_domain: "violet{{ ipam_networks[ipam.violet.network]['domain'] }}"

nginx_upstreams:
  - name: "{{ stevenmagnet_full_domain }}"
    backends:
      - address: "{{ stevenmagnet_full_domain }}:443"
        options: ""

  - name: "{{ violet_full_domain }}"
    backends:
      - address: "{{ violet_full_domain }}:5443"
        options: ""

nginx_vhosts: 
 - server_name: ["luna.sch.bme.hu", "luna"]
   cert_name: luna.sch.bme.hu
   default_server: true
   locations:
    - type: static
      location: "/"
      access_log: true
    - type: static
      location: "/sch-only/"
      access_log: true
      custom: |
        allow 52.66.176.0/21;
        allow 52.66.192.0/24;
        allow 52.66.208.0/22;
        allow 10.51.0.0/16;
        allow 2001:738:2001:2070::/60;
        deny all;
      error_pages:
        "403": "/angery.html"

 - server_name: ["luna.marcsello.com"]
   cert_name: marcsello.com
   locations:
    - type: static
      location: "/"
      access_log: true
      spa: true
#    - type: proxy
#      location: "/ezotv/"
#      access_log: true

 - server_name: ["fakertibutor.sch.bme.hu", "fakertibutor"]
   cert_name: fakertibutor.sch.bme.hu
   locations:
    - type: static
      location: "/"
      access_log: true

 - server_name: ["asztal.sch.bme.hu", "asztal"]
   cert_name: asztal.sch.bme.hu
   locations:
    - type: static
      location: "/"
      access_log: true
  
 - server_name: ["vanefej.sch.bme.hu", "vanefej"]
   cert_name: vanefej.sch.bme.hu
   locations:
    - type: static
      location: "/"
      access_log: true

 - server_name: ["longsmartmotyi.tk"]
   cert_name: longsmartmotyi.tk
   locations:
    - type: static
      location: "/"
      access_log: true

 - server_name: [ "storage.marcsello.com" ]
   cert_name: marcsello.com
   locations:
    - location: /
      type: proxy
      proxy_pass: "https://{{ stevenmagnet_full_domain }}"
      proxy_pass_forwarded_ip: true
      access_log: false
      custom: |
        # this is what the common role installs... TOOD: make this less fragile
        proxy_ssl_trusted_certificate /usr/local/share/ca-certificates/local.crt;
        proxy_ssl_verify on;
        # Disable proxy buffering, because NextCloud should know the exact state of the file transfer
        proxy_buffering off;
   custom: |
    proxy_connect_timeout 30;
    proxy_send_timeout 43200; # 12 hours
    proxy_read_timeout 43200; # 12 hours
    send_timeout 43200; # 12 hours
    client_max_body_size 1024g; # 1TB

    # enable HSTS
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

 - server_name: ["caffe.marcsello.com"]
   cert_name: marcsello.com
   locations:
    - type: static
      location: "/"
      access_log: false
    - location: "~ /openvidu$"
      type: proxy
      proxy_pass: "https://{{ violet_full_domain }}"
      proxy_pass_forwarded_ip: true
      access_log: true
    - location: "/info"
      type: proxy
      proxy_pass: "https://{{ violet_full_domain }}"
      proxy_pass_forwarded_ip: true
      access_log: true
    - location: "/accept-certificate"
      type: proxy
      proxy_pass: "https://{{ violet_full_domain }}"
      proxy_pass_forwarded_ip: true
      access_log: true
   custom: |
    proxy_ssl_trusted_certificate /usr/local/share/ca-certificates/local.crt;
    proxy_ssl_verify on;
