nginx_manage_static_root_dirs: false
nginx_https_proxy_protocol: true
nginx_upstreams: []
# - name:
#   backends:
#     - address: example.net
#       options: ""

nginx_upstreams:
  - name: "stevenmagnet{{ ipam_networks[ipam.stevenmagnet.network]['domain'] }}"
    backends:
      - address: "" # TODO

nginx_vhosts: 
 - server_name: ["luna.sch.bme.hu", "luna"]
   cert_name: luna.sch.bme.hu
   default_server: true
   locations:
    - type: static
      location: "/"
      access_log: true
    - type: static
      location: "/sch-only/"
      access_log: true
      custom: |
        allow 52.66.176.0/21;
        allow 52.66.192.0/24;
        allow 52.66.208.0/22;
        allow 10.51.0.0/16;
        allow 2001:738:2001:2070::/60;
        deny all;
      error_pages:
        "403": "angery.html"

 - server_name: ["luna.marcsello.com"]
   cert_name: marcsello.com
   locations:
    - type: static
      location: "/"
      access_log: true
      spa: true
#    - type: proxy
#      location: "/ezotv/"
#      access_log: true

 - server_name: ["fakertibutor.sch.bme.hu", "fakertibutor"]
   cert_name: luna.sch.bme.hu
   locations:
    - type: static
      location: "/"
      access_log: true

 - server_name: [ "storage.marcsello.com" ]
   cert_name: marcsello.com
   locations:
    - proxy
