- name: "common tasks"
  hosts: all
  roles:
    - common
    - mount

- name: "dns specific tasks"
  hosts: trixie
  roles:
    - { role: internal_dns, tags: ['internal_dns'] }

- name: "webserver specific tasks"
  hosts: web
  roles:
    - { role: nginx, tags: ['nginx'] }
    - { role: haproxy, tags: ['haproxy'] }
    - { role: keepalived, tags: ['keepalived'] }
