- name: "common tasks"
  hosts: all
  roles:
    - common
    - mount

- name: "dns specific tasks"
  hosts: trixie
  roles:
    - { role: internal_dns, tags: ['internal_dns'] }

# Certbot need working dns names so we run it after dns is complete 
- name: "Hosts with certbot"
  hosts:
    - stevenmagnet
    - maud
    - violet
  roles:
    - { role: certbot, tags: ['certbot'] }

- name: "webserver specific tasks"
  hosts: web
  roles:
    - { role: remotecert, tags: ['remotecert'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: haproxy, tags: ['haproxy'] }
    - { role: keepalived, tags: ['keepalived'] }

- name: "haproxy on k8s"
  hosts: k8s
  roles:
     - { role: haproxy, tags: ['haproxy'] }
