nginx_static_root: "/var/www/"

nginx_bind_http_localhost_only: true # it's planned to go trough haproxy
nginx_http_port: 8080

# https listener is needed for clustered setup to protect the data betweeen the vms
nginx_bind_https: false
nginx_ssl_config_snippet_path: "/etc/nginx/snippets/ssl.conf"
nginx_bind_https_localhost_only: false
nginx_https_port: 8443
nginx_https_cert:
  ssl_certificate: ""
  ssl_certificate_key: ""


nginx_upstreams: []
# - name:
#   backends:
#     - address: example.net
#       options: ""

nginx_vhosts: []
# - server_name: [example.net]
#   always_create_static_dir: false
#   default_server: false
#   custom: ""
#   index: "index.html"
#   error_pages: {}
#   locations:
#    - type: static, proxy, custom
#      location: / # this can be regex, if you prefix it with ~
#      access_log: true
#      spa: false
#      custom: ""
#      index: ""
#      proxy_pass: ""
#      proxy_pass_forwarded_ip: true
#      error_pages:
#        "502": /errors/502.html
