mounts: []
# Device should use something unique, not /dev/something...
# The easiest is to check which bus libvirt assings to it, and use that
# - device:
#   Only xfs, ext4 and virtiofs is supported
#   filesystem:
#   mountpoint:
#   readonly: false
