- name: "Check configuration"
  assert:
    that:
      - ipam.keys()|length > 0
      - ipam_networks.keys()|length > 0
      - keepalived_floating_address in ipam.keys()
      - keepalived_vrrp_auth_passwords|length >= 2
      - keepalived_vrrp_instance_name|length > 0
      - keepalived_peers|length >= 1


- name: "Check peer configuration"
  assert:
    that:
      - item in ipam.keys()
  loop: "{{ keepalived_peers }}"

- name: "Install keepalived"
  apt:
    name: keepalived
    state: present
    update_cache: true

# Sometimes keepalived starts after an interface recieves IPv4 address, but not IPv6
# I couldn't find any workaround other than delaying the startup of keepalived alltogether

- name: "Disable keepalived start on bootup"
  systemd:
    name: keepalived.service
    enabled: false

- name: "Install timer to start keepalived"
  copy:
    src: "keepalived.timer"
    dest: "/etc/systemd/system/keepalived.timer"
    owner: root
    group: root
    mode: 0644
  register: keeplived_timer_install_output

# This should not be a handler, because:
# - The effect of this step is required in the next step
# - I don't feel like randomly flushing all handlers in the middle of a play is a good idea
- name: "Systemd deload daemon"
  systemd:
    daemon_reload: true
  when: keeplived_timer_install_output.changed

- name: "Enable keepalived startup timer"
  systemd:
    name: keepalived.timer
    enabled: true

- name: "Install keepalived config"
  template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
    owner: root
    group: root
    mode: 0644
  notify: "Reload keepalived"


# This should be added to the end of every role, since ansible can't scope handlers for a role
- name: "Flush handlers at the end of the role"
  meta: flush_handlers
