- name: "Remove ubuntu-server package"
  apt: 
    state: absent
    name: ubutu-server
    autoremove: true

- name: clean motd
  file:
    state: absent
    path: /etc/update-motd.d/{{ item }}
  with_items:
    - 10-help-text
    - 50-landscape-sysinfo
    - 50-motd-news
    - 91-release-upgrade

- name: "disable systemd-resolved"
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true

- name: check if resolvconf linked
  stat:
    path: /etc/resolv.conf
  register: link

- name: remove symlink
  file:
    path: /etc/resolv.conf
    state: absent
  when: link.stat.islnk is defined and link.stat.islnk

- name: "install resolvconf"
  apt:
    name: resolvconf
    state: present

- name: Remove snapd from Ubuntu
  apt:
    name: snapd
    state: absent
    purge: true
    autoremove: true

- name: Remove snapd-related directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /snap
    - /var/snap
    - /var/lib/snapd
    - "/home/{{ ansible_user }}/snap"
